-- Step 5A.1: Create a temporary table with patient ID ranges for 10 batches
CREATE OR REPLACE TEMPORARY TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BATCHES AS (
    WITH PatientRanges AS (
        SELECT 
            MIN(CVS_CENTR_PAT_NBR) as MIN_PAT_NBR,
            MAX(CVS_CENTR_PAT_NBR) as MAX_PAT_NBR,
            (MAX_PAT_NBR - MIN_PAT_NBR)/10 as RANGE_SIZE
        FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_WITH_DRUG
    )
    SELECT DISTINCT
        CVS_CENTR_PAT_NBR,
        FLOOR((CVS_CENTR_PAT_NBR - MIN_PAT_NBR)/RANGE_SIZE) + 1 as BATCH_ID
    FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_WITH_DRUG
    CROSS JOIN PatientRanges
    WHERE FLOOR((CVS_CENTR_PAT_NBR - MIN_PAT_NBR)/RANGE_SIZE) + 1 <= 10
);

-- Validate batch sizes
SELECT 
    BATCH_ID,
    COUNT(*) as RECORDS_IN_BATCH,
    COUNT(DISTINCT CVS_CENTR_PAT_NBR) as UNIQUE_PATIENTS_IN_BATCH,
    MIN(CVS_CENTR_PAT_NBR) as MIN_PAT_NBR,
    MAX(CVS_CENTR_PAT_NBR) as MAX_PAT_NBR
FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BATCHES
GROUP BY BATCH_ID
ORDER BY BATCH_ID;
